site_name: Datacollect
site_url: https://lfwa.github.io/datacollect/

repo_name: lfwa/datacollect
repo_url: https://github.com/lfwa/datacollect

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - content.code.annotate

plugins:
  - search
  - mkdocstrings

extra:
  generator: false

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

nav:
  - Home: index.md
  - Tutorials:
      - tutorials/graph_collector_tutorial.md
      - tutorials/collector_tutorial.md
  - API:
      - api/environments.md
      - api/policies.md
