name: Publish

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
          python -m pip install --upgrade pip
          pip --version

    - name: Install Poetry
      run: |
        pip install poetry
        poetry --version

    - name: Build and publish
      if: startsWith(github.ref, 'refs/tags')
      run: |
        poetry version $(git describe --tags --abbrev=0)
        poetry build
        poetry publish \
            --username __token__ \
            --password ${{ secrets.PYPI_TOKEN }}
