name: Publish

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Upgrade pip
      run: |
          python -m pip install --upgrade pip
          pip --version

    - name: Install Poetry
      run: |
        pip install poetry
        poetry --version

    - name: Build and publish
      if: startsWith(github.ref, 'refs/tags')
      run: |
        poetry version $(git describe --tags --abbrev=0)
        poetry build
        poetry publish \
            --username __token__ \
            --password ${{ secrets.PYPI_TOKEN }}
